// Generated by gencpp from file um_acc/CarSignal.msg
// DO NOT EDIT!


#ifndef UM_ACC_MESSAGE_CARSIGNAL_H
#define UM_ACC_MESSAGE_CARSIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace um_acc
{
template <class ContainerAllocator>
struct CarSignal_
{
  typedef CarSignal_<ContainerAllocator> Type;

  CarSignal_()
    : distance(0)
    , rpm(0)
    , hello()  {
    }
  CarSignal_(const ContainerAllocator& _alloc)
    : distance(0)
    , rpm(0)
    , hello(_alloc)  {
    }



   typedef uint64_t _distance_type;
  _distance_type distance;

   typedef uint64_t _rpm_type;
  _rpm_type rpm;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hello_type;
  _hello_type hello;




  typedef boost::shared_ptr< ::um_acc::CarSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::um_acc::CarSignal_<ContainerAllocator> const> ConstPtr;

}; // struct CarSignal_

typedef ::um_acc::CarSignal_<std::allocator<void> > CarSignal;

typedef boost::shared_ptr< ::um_acc::CarSignal > CarSignalPtr;
typedef boost::shared_ptr< ::um_acc::CarSignal const> CarSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::um_acc::CarSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::um_acc::CarSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace um_acc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'um_acc': ['/home/ubuntu/rccar_catkin_ws/src/um_acc/msg', '/home/ubuntu/rccar_catkin_ws/src/um_acc/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::um_acc::CarSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::um_acc::CarSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um_acc::CarSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um_acc::CarSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um_acc::CarSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um_acc::CarSignal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::um_acc::CarSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e566582175e27ba4318fc31985507438";
  }

  static const char* value(const ::um_acc::CarSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe566582175e27ba4ULL;
  static const uint64_t static_value2 = 0x318fc31985507438ULL;
};

template<class ContainerAllocator>
struct DataType< ::um_acc::CarSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "um_acc/CarSignal";
  }

  static const char* value(const ::um_acc::CarSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::um_acc::CarSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 distance\n\
uint64 rpm\n\
string hello\n\
";
  }

  static const char* value(const ::um_acc::CarSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::um_acc::CarSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.rpm);
      stream.next(m.hello);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CarSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::um_acc::CarSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::um_acc::CarSignal_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.distance);
    s << indent << "rpm: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.rpm);
    s << indent << "hello: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hello);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UM_ACC_MESSAGE_CARSIGNAL_H
