// Generated by gencpp from file um_acc/CarState_L.msg
// DO NOT EDIT!


#ifndef UM_ACC_MESSAGE_CARSTATE_L_H
#define UM_ACC_MESSAGE_CARSTATE_L_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace um_acc
{
template <class ContainerAllocator>
struct CarState_L_
{
  typedef CarState_L_<ContainerAllocator> Type;

  CarState_L_()
    : y(0.0)
    , v(0.0)
    , phi(0.0)
    , r(0.0)  {
    }
  CarState_L_(const ContainerAllocator& _alloc)
    : y(0.0)
    , v(0.0)
    , phi(0.0)
    , r(0.0)  {
    }



   typedef double _y_type;
  _y_type y;

   typedef double _v_type;
  _v_type v;

   typedef double _phi_type;
  _phi_type phi;

   typedef double _r_type;
  _r_type r;




  typedef boost::shared_ptr< ::um_acc::CarState_L_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::um_acc::CarState_L_<ContainerAllocator> const> ConstPtr;

}; // struct CarState_L_

typedef ::um_acc::CarState_L_<std::allocator<void> > CarState_L;

typedef boost::shared_ptr< ::um_acc::CarState_L > CarState_LPtr;
typedef boost::shared_ptr< ::um_acc::CarState_L const> CarState_LConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::um_acc::CarState_L_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::um_acc::CarState_L_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace um_acc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'um_acc': ['/home/ubuntu/rccar_catkin_ws/src/um_acc/msg', '/home/ubuntu/rccar_catkin_ws/src/um_acc/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::um_acc::CarState_L_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::um_acc::CarState_L_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um_acc::CarState_L_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um_acc::CarState_L_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um_acc::CarState_L_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um_acc::CarState_L_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::um_acc::CarState_L_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e4939b536e65d0f1c171d857d476271";
  }

  static const char* value(const ::um_acc::CarState_L_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e4939b536e65d0fULL;
  static const uint64_t static_value2 = 0x1c171d857d476271ULL;
};

template<class ContainerAllocator>
struct DataType< ::um_acc::CarState_L_<ContainerAllocator> >
{
  static const char* value()
  {
    return "um_acc/CarState_L";
  }

  static const char* value(const ::um_acc::CarState_L_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::um_acc::CarState_L_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 y\n\
float64 v\n\
float64 phi\n\
float64 r\n\
";
  }

  static const char* value(const ::um_acc::CarState_L_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::um_acc::CarState_L_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y);
      stream.next(m.v);
      stream.next(m.phi);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CarState_L_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::um_acc::CarState_L_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::um_acc::CarState_L_<ContainerAllocator>& v)
  {
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UM_ACC_MESSAGE_CARSTATE_L_H
