// Generated by gencpp from file um_acc/ComputeControl_L.msg
// DO NOT EDIT!


#ifndef UM_ACC_MESSAGE_COMPUTECONTROL_L_H
#define UM_ACC_MESSAGE_COMPUTECONTROL_L_H

#include <ros/service_traits.h>


#include <um_acc/ComputeControl_LRequest.h>
#include <um_acc/ComputeControl_LResponse.h>


namespace um_acc
{

struct ComputeControl_L
{

typedef ComputeControl_LRequest Request;
typedef ComputeControl_LResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeControl_L
} // namespace um_acc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::um_acc::ComputeControl_L > {
  static const char* value()
  {
    return "e1ca6f126ba6e72cf211ce250f75793e";
  }

  static const char* value(const ::um_acc::ComputeControl_L&) { return value(); }
};

template<>
struct DataType< ::um_acc::ComputeControl_L > {
  static const char* value()
  {
    return "um_acc/ComputeControl_L";
  }

  static const char* value(const ::um_acc::ComputeControl_L&) { return value(); }
};


// service_traits::MD5Sum< ::um_acc::ComputeControl_LRequest> should match 
// service_traits::MD5Sum< ::um_acc::ComputeControl_L > 
template<>
struct MD5Sum< ::um_acc::ComputeControl_LRequest>
{
  static const char* value()
  {
    return MD5Sum< ::um_acc::ComputeControl_L >::value();
  }
  static const char* value(const ::um_acc::ComputeControl_LRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::um_acc::ComputeControl_LRequest> should match 
// service_traits::DataType< ::um_acc::ComputeControl_L > 
template<>
struct DataType< ::um_acc::ComputeControl_LRequest>
{
  static const char* value()
  {
    return DataType< ::um_acc::ComputeControl_L >::value();
  }
  static const char* value(const ::um_acc::ComputeControl_LRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::um_acc::ComputeControl_LResponse> should match 
// service_traits::MD5Sum< ::um_acc::ComputeControl_L > 
template<>
struct MD5Sum< ::um_acc::ComputeControl_LResponse>
{
  static const char* value()
  {
    return MD5Sum< ::um_acc::ComputeControl_L >::value();
  }
  static const char* value(const ::um_acc::ComputeControl_LResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::um_acc::ComputeControl_LResponse> should match 
// service_traits::DataType< ::um_acc::ComputeControl_L > 
template<>
struct DataType< ::um_acc::ComputeControl_LResponse>
{
  static const char* value()
  {
    return DataType< ::um_acc::ComputeControl_L >::value();
  }
  static const char* value(const ::um_acc::ComputeControl_LResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UM_ACC_MESSAGE_COMPUTECONTROL_L_H
