// Generated by gencpp from file um_acc/Pwm.msg
// DO NOT EDIT!


#ifndef UM_ACC_MESSAGE_PWM_H
#define UM_ACC_MESSAGE_PWM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace um_acc
{
template <class ContainerAllocator>
struct Pwm_
{
  typedef Pwm_<ContainerAllocator> Type;

  Pwm_()
    : vel_pwm(0)
    , steer_pwm(0)  {
    }
  Pwm_(const ContainerAllocator& _alloc)
    : vel_pwm(0)
    , steer_pwm(0)  {
    }



   typedef uint16_t _vel_pwm_type;
  _vel_pwm_type vel_pwm;

   typedef uint16_t _steer_pwm_type;
  _steer_pwm_type steer_pwm;




  typedef boost::shared_ptr< ::um_acc::Pwm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::um_acc::Pwm_<ContainerAllocator> const> ConstPtr;

}; // struct Pwm_

typedef ::um_acc::Pwm_<std::allocator<void> > Pwm;

typedef boost::shared_ptr< ::um_acc::Pwm > PwmPtr;
typedef boost::shared_ptr< ::um_acc::Pwm const> PwmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::um_acc::Pwm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::um_acc::Pwm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace um_acc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'um_acc': ['/home/ubuntu/rccar_catkin_ws/src/um_acc/msg', '/home/ubuntu/rccar_catkin_ws/src/um_acc/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::um_acc::Pwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::um_acc::Pwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um_acc::Pwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um_acc::Pwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um_acc::Pwm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um_acc::Pwm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::um_acc::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae10eabeb4f7922a099183b45f9137bb";
  }

  static const char* value(const ::um_acc::Pwm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae10eabeb4f7922aULL;
  static const uint64_t static_value2 = 0x099183b45f9137bbULL;
};

template<class ContainerAllocator>
struct DataType< ::um_acc::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "um_acc/Pwm";
  }

  static const char* value(const ::um_acc::Pwm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::um_acc::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 vel_pwm\n\
uint16 steer_pwm\n\
";
  }

  static const char* value(const ::um_acc::Pwm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::um_acc::Pwm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel_pwm);
      stream.next(m.steer_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Pwm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::um_acc::Pwm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::um_acc::Pwm_<ContainerAllocator>& v)
  {
    s << indent << "vel_pwm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.vel_pwm);
    s << indent << "steer_pwm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.steer_pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UM_ACC_MESSAGE_PWM_H
