// Generated by gencpp from file um_acc/Sensor.msg
// DO NOT EDIT!


#ifndef UM_ACC_MESSAGE_SENSOR_H
#define UM_ACC_MESSAGE_SENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace um_acc
{
template <class ContainerAllocator>
struct Sensor_
{
  typedef Sensor_<ContainerAllocator> Type;

  Sensor_()
    : distance(0.0)
    , rpm(0.0)  {
    }
  Sensor_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , rpm(0.0)  {
    }



   typedef double _distance_type;
  _distance_type distance;

   typedef double _rpm_type;
  _rpm_type rpm;




  typedef boost::shared_ptr< ::um_acc::Sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::um_acc::Sensor_<ContainerAllocator> const> ConstPtr;

}; // struct Sensor_

typedef ::um_acc::Sensor_<std::allocator<void> > Sensor;

typedef boost::shared_ptr< ::um_acc::Sensor > SensorPtr;
typedef boost::shared_ptr< ::um_acc::Sensor const> SensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::um_acc::Sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::um_acc::Sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace um_acc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'um_acc': ['/home/ubuntu/rccar_catkin_ws/src/um_acc/msg', '/home/ubuntu/rccar_catkin_ws/src/um_acc/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::um_acc::Sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::um_acc::Sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um_acc::Sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um_acc::Sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um_acc::Sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um_acc::Sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::um_acc::Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d74f605f71828dbc9937816ed80a112";
  }

  static const char* value(const ::um_acc::Sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d74f605f71828dbULL;
  static const uint64_t static_value2 = 0xc9937816ed80a112ULL;
};

template<class ContainerAllocator>
struct DataType< ::um_acc::Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "um_acc/Sensor";
  }

  static const char* value(const ::um_acc::Sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::um_acc::Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n\
float64 rpm\n\
";
  }

  static const char* value(const ::um_acc::Sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::um_acc::Sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.rpm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::um_acc::Sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::um_acc::Sensor_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "rpm: ";
    Printer<double>::stream(s, indent + "  ", v.rpm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UM_ACC_MESSAGE_SENSOR_H
